import os

env = Environment()
platform = env['PLATFORM']

if platform == 'darwin':
    env.Append(CCFLAGS = "-std=c++0x -Wall -I/usr/include/python2.7 -I.. -I/Users/catanzar/boost_1_47_0 -g")
else:
    env.Append(CCFLAGS = "-std=c++0x -Wall -I/usr/include/python2.7 -I.. -g")

for x in ['coresyntax.cpp', 'coretypes.cpp']:
    basename, extension = os.path.splitext(str(x))
    if platform == 'darwin':
        env.SharedLibrary(target=basename, source=x, LIBPATH=['/Users/catanzar/boost_1_47_0/stage/lib'], LIBS=['boost_python'], SHLIBPREFIX='', SHLIBSUFFIX='.so', LINKFLAGS='-F/System/Library/Frameworks/ -framework Python')
    else:
        env.SharedLibrary(target=basename, source=x, LIBS=['boost_python'], SHLIBPREFIX='')